const msg = {
    success: "Ok",
    notFound: "Not Found",
    mandatoryPassword: "password is mandatory",
    invalidOtp: "otp is invalid",
    invalidReferalCode: "invalid refferal code",
    invalidPassword: "Password is invalid",
    userExist: "User already exists",
    chatExist: "chat already exists",
    teacherNotFoundForThisSchool:"Teacher not assigned in this school",
    isEmailVerified: "Email is not varified",
    userSignedupWihGoogle: "User is signed up with google.Try to login using google",
    userSignedupWithFacebook: "User is signed up with facebook.Try login using facebook",
    requiredOtp: "otp is required",
    email: "please provide email",
    timing: "timing not assind",
    userNotFound: "User not found",
    pleaseSelectQuestionType:"please Select Question Type for add test",
    password_updated: "Password is successfully updated",
    userNotVerified: "User is unverified. Please check your mail to verify",
    loggedIn: "Successfully logIn",
    expireOtp: "otp is expired",
    incorrectOTP: "otp is incorrect",
    requireClassIdAndSessionId: "require ClassId And SessionId",
    duplicateEmail: "Email already exists",
    duplicatePhone: "Contact number already exists",
    duplicateUnverifiedEmail: "This email Id is registered, but not verified",
    duplicateUnverifiedPhone: "This phone is registered, but not verified",
    invalidCredentials: "Invalid credentials",
    badReq: "Bad request",
    school: "school is not exits",
    YouDoNotHavePassword: "Please make sure you dont have password you have to forget password",
    serverError: 'Something went wrong, please try again...',
    passwordRequired: "Password required",
    emailRequired: "Email is Required",
    invalidEmail: "Email address is invalid",
    resetPassword: 'Reset password link has been send.Please check your emails',
    resetPasssuccessful: "password has been successfully updated",
    userDeleted: 'User is successfully deleted',
    NotExist: "Do not exist",
    alreadyViewed: "already viewed",
    orderNotexist: "Order do not exist",
    NotCreated: "Do not created, try again",
    messageLimit: "chat message limit reached for current plan",
    requestLimit: "request limit reached for current plan",
    invalidSender: "invalid sender",
    failedTransaction: "transaction failed",
    CouponNotExist: "Coupon dose not exist",
    actionForbidden: "This action is forbidden. You don't have permission to do this",
    notAvailable: 'Not available',
    notValidCode: 'Code is not valid',
    unauthorisedRequest: 'Unauthorised request',
    passwordUpdated: 'Password updated successfully',
    invalidVerficationCode: 'Please enter a valid verification code',
    invalidForgotCode: 'Invalid forgot code',
    invalidCategoryId: 'Invalid category id',
    invalidSubcategoryId: 'Invalid subcategory id',
    invalidSubSubcategoryId: 'Invalid sub sub category id',
    invalidProductId: 'Invalid product id',
    removedFromWishlist: 'Item successfully removed from wishlist',
    removedFromSaveForLater: 'Item successfully removed from save for later',
    addedInWishlist: 'Item successfully added in wishlist',
    addedInVocab: 'word successfully added.',
    addedInCYH: 'Item successfully added in CYH',
    addedInSaveForLater: 'Item successfully added in save for later',
    invalidId: 'Please enter valid id',
    invalidUserId: 'Please enter valid User id',
    invalidAddressId: 'Please enter valid Address id',
    productNotExist: 'This product dose not exist',
    invalidBrandId: 'Provided brand id is invalid',
    unexpectedError: 'Some unexpected error occured. Please try again later',
    unverifiedForgotPasswordReq: 'Invalid request. The forgot password code is not verified',
    invalidBlogId: 'Please enter valid blog id',
    seasonNotValid: 'This season is invalid',
    noSeasonAvailable: 'No season is available at this moment',
    OrderCanceledSuccessfully: 'Your Order has been canceled successsfully',
    tooLateToCancelOrder: 'Now you are late to cancel your order',
    invalidDetails: "Invalid Id",
    NotExistOrNotActive: "Not Exist Or Not Active",
    OrderListIsEmpty: "Order list is empty",
    speedListIsEmpty: "speed date chat is empty",
    canNotDeliverAtThisPin: "Can not deliver at this PinCode",
    noProductAvailableForShipping: "No product available for shipping",
    productIsOutOfStock: "This product is out of stock",
    paymentFailed: "Payment failed",
    notSaved: "Not saved",
    otpVerified: "OTP has been verified",
    otpNotVerified: "OTP is invalid",
    couponCodeCanNotBeApplied: "Your payable ammount is less then given minimum ammount. So that coupon can not be applied",
    couponNotExist: "This coupon dose not exist",
    couponIsNotApplicable: "This coupon code is not applicable for you",
    hintTitleRequired: "Hint Title is required",
    hintContentRequired: "Hint Content is required",
    questionRequired: "Question Required.",
    questionIdRequired: "Question Id Required.",
    answerIdRequired: "Answer Id required",
    invalidHintId: "Hint Id Invalid",
    invalidBalance: 'insufficient balance',
    blockedByuser: 'Blocked By User',
    norewardearn: "You Have no rewards Yet",
    blockByUser: "You Have been Blocked By Admin",
    CardnotExist: 'card not exist',
    UsernotExist: 'User Not Exist',
    GiftNotFound: 'Gift Not Exist',
    hotelnotExist: 'hotelNotExist',
    nameismandatory: "Firstname is mandatory",
    onepropertyisrequired: "one property of mother and father is required",
    addressrequired: "one property of address is required",
    idrequired: "Id is required",
    incorrectPassword: 'Password is Incorrect',
    noshoolregisterd: 'School is not registerd Yet.',
    alreadyMarked: "Your attendance has been already Marked",
    statusRequired: "Attandance status required",
    classAlreadyExist: "Class already Exist",
    classNotExist: "Class Not exists",
    sectionExist: "Section Already Exist",
    teacherNotFound: "Teacher Not Found",
    studentNotFound: "Student Not Found",
    noStudentFound: "No Student Found ",
    classIsRequired: "Class is required",
    assignmentNotFound: "Assignment Not Found",
    DateIsRequired: "Date is required",
    schooolIdRequired: "School id is required",
    subjectNotFound: "Subject List is Empty.",
    AttendanceNotFound: "Attendance not found for this user",
    already:"You have already marked leave",
    noFeesExist: "Fees not found",
    noTestExist: "Test not exist",
    classIdRequired: "Class id required",
    sectionIdRequired: "Section id required",
    homeworkNotFound: "Homework not found",
    studentIdRequired: "Student id required",
    sectionNotFound: "Section not found",
    subjectIdRequired: "Subject id is required",
    assignmentIdRequired: "Assignment id is required",
    syllabusIdRequired: "Syllabus id is required",
    syllabusNotFound: "Syllabus not found",
    invalidSectionId: "Please provide a Valid Section Id",
    invalidTimeTableId: "Please provide a Valid Timetable id",
    teacherIdRequired: "Please provide a Teacher id",
    marksrequired: "Please provide obtained marks",
    alreadyResultComplied: "You Already Compiled Result For This Test"
}

module.exports = { msg };